name: octaneIntegration2
on:
  workflow_run:
    workflows: [Maven Tests]
    types: [requested, in_progress, completed]
  pull_request:
    types: [opened, edited, closed, reopened]
jobs:
  octane_integration_job:
    runs-on: octane
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v25.2.1
        id: gitHubActionsIntegration
        with:
          octaneUrl: https://felix-1.almoctane.com/
          octaneSharedSpace: 1001
          octaneWorkspace: 1002
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          serverBaseUrl: https://github.com/DAlmasan
          pipelineNamePattern: '${workflow_name}'
          unitTestResultsGlobPattern: "**/*.xml"
          gherkinTestResultsGlobPattern: "**/*.xml"
