name: Test Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
    inputs:
      testsToRun:
        type: string
        default: "*"
      suiteId:
         type: number
         default: "0"
      suiteRunId:
         type: number
         default: "0"
      executionId:
         type: number
         default: "0"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Log workflow execution parameters
        run: |
          echo "execution_parameter:: $(echo '${{ toJson(github.event.inputs) }}' | jq -c .)"
          
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 1: Convert testsToRun parameter
      - name: Convert testsToRun parameter
        id: convert_tests
        run: |
          output=$(npx @opentext/sdp-sdm-tests-to-run-conversion --framework="junit" --testsToRun="${{ github.event.inputs.testsToRun }}" --logLevel=0)
          echo "converted_tests=$output" >> $GITHUB_ENV

      # Step 2: Run Maven tests (ignore failures)
      - name: Run JUnit Tests
        #run: mvn test -B -Dsurefire.testFailureIgnore=true -Dsurefire.failIfNoSpecifiedTests=false -Dtest="${converted_tests// /}"
        run: mvn test -Dtest="$converted_tests"


      # Step 3: Upload test results (Surefire)
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: |
            **/target/surefire-reports/*.xml
            **/target/surefire-reports/*.txt
